(setenv "PATH"
    (concat
     "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow" ";"
    "C:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.0\\Framework\\v4.0\\" ";"
    "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VSTSDB\\Deploy" ";"
    "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\IDE\\" ";"
    "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\BIN" ";"
    "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools" ";"
    "C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319" ";"
    "C:\\windows\\Microsoft.NET\\Framework\\v3.5" ";"
    "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\VCPackages" ";"
    "C:\\Program Files (x86)\\HTML Help Workshop" ";"
    "C:\\Program Files (x86)\\HTML Help Workshop" ";"
    "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Team Tools\\Performance Tools" ";"
    "C:\\Program Files (x86)\\Windows Kits\\8.0\\bin\\x86" ";"
    "C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.0A\\bin\\NETFX 4.0 Tools" ";"
    "C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\bin\\" ";"
    "C:\\users\\herbert19lee\\.emacs.d\\personal\\dos" ";"
     (getenv "PATH")))
